### ISSUE TITLE
feature request: make date format configurable

### ISSUE THREAD

**Issue by ross-oreto** [ZhongjunTian/Spring-Repository-Specification#2]
Make the simple date format in WhereSpecification configurable by checking the spring properties file for a property which defines the format.
Something like
```com.jontian.specification.dateformat="yyyy-MM-dd"```
which will override the default if present.

**Comment by ZhongjunTian** [comment]
That's a good idea! Actually, I was going to make it configurable. Thanks for you advice!

**Comment by ZhongjunTian** [comment]
Hi.
Read spring properties require Spring Context or making this tool managed by Spring. But I am not going to coupling with Spring at this point. As kind of trade off,  I added 2 setters for this dataFormat, once static format, once instance specific value. 
please check WhereSpecification.java
